content:
  - name: offerte
    label: Offerte
    path: src/contentPageCMS/offerte
    filename: "{fields.titolo}.md"
    type: collection
    fields:
      - name: img
        label: Immagine prodotto
        type: image
        required: true

      - name: titolo
        label: Titolo
        type: string
        required: true

      - name: descrizione
        label: Descrizione
        type: string
        description: Max 356 characters
        required: false

      - name: prezzoOriginale
        label: Prezzo originale
        type: string
        required: false

      - name: prezzoScontato
        label: Prezzo scontato
        type: string
        required: true
#  - name: impostazioniGlobali
#    label: Impostazioni Globali
#    path: src/contentPageCMS
#    filename: "global-settings.md"
#    type: collection
#    fields:
#      - name: dataScadenzaOfferte
#        label: Data Scadenza Offerte
#        type: date
#        required: true
      
media:
  input: public/images/offertePageCMS
  output: /images/offertePageCMS
  extensions: [png, webp, jpg, jpeg]